#!/usr/bin/env python3
"""Fail if the committed evaluation report was produced by different code (P3-15).

    PYTHONPATH="$PWD" python ml/scripts/check_report_fresh.py

WHAT THIS CHECKS, AND WHAT IT DELIBERATELY DOES NOT
----------------------------------------------------
It does not verify the numbers. It cannot: the benchmark chips are 533 MB and
gitignored, so CI has no data to score against, and a gate that skips when data is
missing reports green while checking nothing -- which is worse than having no gate,
because people trust it.

What it verifies is that ``reports/evaluation.md`` was generated by the code
currently on the branch. Change Otsu, change the postprocessing, change the loss --
and this fails until the report is regenerated. That closes the specific failure
this project has already had once: numbers drifting away from the code that
produced them, quietly, while everything still passes.

The honest summary of the guarantee: **not "these numbers are right", but "these
numbers came from this code".** The first needs data in CI; the second is the one
that rots silently.

NOTHING MAY RUN BEFORE THIS IN CI
---------------------------------
This gate was briefly defeated by a step that stamped the current fingerprint into
the report immediately before running it. That made the comparison unconditional:
the recorded value was whatever the code hashed to, so it always matched. Measured,
not argued -- inverting the water polarity in ``ml/pipeline/baseline.py``, which
turns every water measurement into a land measurement, passed green while the
report still published IoU 0.259.

The escape hatch that step was reaching for is real and still exists, but it lives
in ``ml/scripts/waive_report.py``, is run by a person, and leaves a signed row in a
committed file. See the module docstring there.
"""

from __future__ import annotations

import sys
from pathlib import Path

from ml.scripts.report_freshness import (
    REGENERATE,
    REPORTS,
    WAIVERS,
    changed_modules,
    code_fingerprint,
    read_recorded_fingerprint,
    read_waivers,
)


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    return max(check(repo_root, report, modules) for report, modules in REPORTS.items())


def check(repo_root: Path, report: Path, modules: tuple[str, ...]) -> int:
    if not (repo_root / report).is_file():
        print(
            f"{report} is missing.\n\n"
            "Every number quoted about this subsystem must come from that file. "
            f"Generate it with:\n{REGENERATE[report]}",
            file=sys.stderr,
        )
        return 1

    recorded = read_recorded_fingerprint(repo_root, report)
    if recorded is None:
        print(
            f"{report} carries no code fingerprint, so it cannot be checked for "
            "staleness. It was probably hand-edited -- regenerate it.",
            file=sys.stderr,
        )
        return 1

    current = code_fingerprint(repo_root, modules)
    if recorded == current:
        print(f"{report} is current (fingerprint {current})")
        return 0

    waiver = read_waivers(repo_root).get(current)
    if waiver is not None:
        # Loud on purpose. A waiver is someone's assertion that a change could not
        # move a number, and the whole value of it is that a human sees it said out
        # loud rather than finding a hash that quietly matched.
        print(
            f"{report} does not match the code, and the difference is WAIVED.\n\n"
            f"  recorded fingerprint: {recorded}\n"
            f"  current  fingerprint: {current}\n"
            f"  waiver:               {waiver}\n\n"
            f"The numbers below were produced by earlier code. Someone asserted in "
            f"{WAIVERS} that the difference cannot move them. If that assertion "
            "looks wrong, regenerate the report -- do not add another waiver."
        )
        return 0

    changed = changed_modules(repo_root, modules)
    detail = (
        "  changed since the report was generated:\n"
        + "".join(f"    - {module}\n" for module in changed)
        if changed
        else "  (per-module detail unavailable: the fingerprint sidecar is missing)\n"
    )

    print(
        f"{report} is stale.\n\n"
        f"  recorded fingerprint: {recorded}\n"
        f"  current  fingerprint: {current}\n"
        f"{detail}\n"
        "An analysis module changed since the report was generated, so the numbers "
        "in it were produced by different code. Regenerate:\n"
        f"{REGENERATE[report]}\n\n"
        "If the change provably cannot move a number -- a docstring, a type "
        "annotation, an operator that returns an identical value -- record a waiver "
        "instead. It needs your name and a reason, and it lands in a committed file "
        "a reviewer reads:\n"
        '    PYTHONPATH="$PWD" python ml/scripts/waive_report.py \\\n'
        '        --by "Your Name" --reason "why this cannot move a number"',
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
