#!/usr/bin/env python3
"""Fail if the committed evaluation report was produced by different code (P3-15).

    PYTHONPATH="$PWD" python ml/scripts/check_report_fresh.py

WHAT THIS CHECKS, AND WHAT IT DELIBERATELY DOES NOT
----------------------------------------------------
It does not verify the numbers. It cannot: the benchmark chips are 533 MB and
gitignored, so CI has no data to score against, and a gate that skips when data is
missing reports green while checking nothing — which is worse than having no gate,
because people trust it.

What it verifies is that ``reports/evaluation.md`` was generated by the code
currently on the branch. Change Otsu, change the postprocessing, change the loss —
and this fails until the report is regenerated. That closes the specific failure
this project has already had once: numbers drifting away from the code that
produced them, quietly, while everything still passes.

The honest summary of the guarantee: **not "these numbers are right", but "these
numbers came from this code".** The first needs data in CI; the second is the one
that rots silently.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from ml.scripts.generate_report import code_fingerprint

REPORT = Path("reports/evaluation.md")
FINGERPRINT = re.compile(r"^\|\s*code fingerprint\s*\|\s*`([0-9a-f]+)`\s*\|", re.M)


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    report = repo_root / REPORT

    if not report.is_file():
        print(
            f"{REPORT} is missing.\n\n"
            "Every number quoted about this subsystem must come from that file. "
            "Generate it with:\n"
            '    PYTHONPATH="$PWD" python ml/scripts/generate_report.py',
            file=sys.stderr,
        )
        return 1

    match = FINGERPRINT.search(report.read_text())
    if match is None:
        print(
            f"{REPORT} carries no code fingerprint, so it cannot be checked for "
            "staleness. It was probably hand-edited — regenerate it.",
            file=sys.stderr,
        )
        return 1

    recorded = match.group(1)
    current = code_fingerprint(repo_root)

    if recorded != current:
        print(
            f"{REPORT} is stale.\n\n"
            f"  recorded fingerprint: {recorded}\n"
            f"  current  fingerprint: {current}\n\n"
            "An analysis module changed since the report was generated, so the "
            "numbers in it were produced by different code. Regenerate:\n"
            "    python3 fetch_sen1floods11.py --split all --count 400\n"
            '    PYTHONPATH="$PWD" python ml/scripts/generate_report.py\n\n'
            "If the change genuinely cannot move a number — a docstring, a type "
            "annotation — remove that module from FINGERPRINTED in "
            "ml/scripts/generate_report.py rather than regenerating on every edit.",
            file=sys.stderr,
        )
        return 1

    print(f"{REPORT} is current (fingerprint {current})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
