"""The result of a mission run: either an analysis, or an abstention.

Design rule
-----------
    Absence of an answer is a first-class result, never a placeholder.

There are exactly two outcomes and no third. In particular there is no "empty
analysis with zeroed values", because a zero hectare figure and "we could not
measure" are different statements and a user acting on a flood map needs to know
which one they are looking at.

This is also what replaces the "deterministic fixture fallback" that the P3
specification authorises in three places (its section 15 agent prompt, issue P3-14,
and the section 10 failure-mode table). A fixture standing in for a failed
inference is a number no satellite produced, presented as though one did. The two
legitimate degraded behaviours are:

1. return an :class:`Abstention` with a machine-readable reason, or
2. fall back to the deterministic Otsu baseline and label the result as such --
   a real computation on real data, just a simpler one.

Both are demonstrable and both are honest. "The neural model timed out, so the
system fell back to a deterministic physical method and told you so" is a good
answer to a reviewer. A canned result is not.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Annotated, Literal

from pydantic import Field

from ml.contracts.base import Strict
from ml.contracts.confidence import Confidence
from ml.contracts.measurement import Measurement
from ml.contracts.scene import SceneRef


class AbstentionReason(str, Enum):
    """Machine-readable reasons the subsystem may decline to answer.

    Deliberately a closed set: a new way of failing requires adding a member here,
    which forces a decision about how the UI should present it and gives the
    observability layer a stable label to count. A free-text reason would make the
    abstention-rate-by-reason dashboard -- the single most informative health
    signal this subsystem has -- useless.
    """

    #: No usable acquisition exists in the requested window.
    NO_SCENES_IN_WINDOW = "no_scenes_in_window"
    #: Optical is unusable and the question requires optical.
    CLOUD_EXCEEDS_THRESHOLD = "cloud_exceeds_threshold"
    #: The available sensor physically cannot answer the question asked
    #: (e.g. a spectral question under cloud -- SAR cannot substitute).
    SENSOR_CANNOT_ANSWER = "sensor_cannot_answer"
    #: Candidate scenes differ in relative orbit or pass direction.
    ORBIT_MISMATCH = "orbit_mismatch"
    #: The AOI falls outside the coverage of every available provider.
    AOI_OUTSIDE_COVERAGE = "aoi_outside_coverage"
    #: Provider holds the product offline (e.g. Bhoonidhi ``Online: "N"``), so it
    #: cannot be fetched through the API at all.
    PRODUCT_OFFLINE = "product_offline"
    #: The deterministic baseline and the learned model disagree beyond the
    #: configured threshold. Flagged rather than smoothed over.
    MODELS_DISAGREE = "models_disagree"
    #: AOI exceeds the resource bound; refused rather than attempted.
    AOI_TOO_LARGE = "aoi_too_large"
    #: Input failed preflight validation (bands, units, dtype, dimensions, CRS).
    INPUT_FAILED_PREFLIGHT = "input_failed_preflight"
    #: Otsu found no separable threshold -- the histogram is unimodal, meaning the
    #: scene is all water or all land, or the change signal is absent.
    NO_SEPARABLE_THRESHOLD = "no_separable_threshold"


class Abstention(Strict):
    """A declined answer, with enough detail to be actionable.

    ``scenes_seen`` matters: showing what was examined before declining is what
    distinguishes a considered refusal from a failure. A user who is told
    "no Sentinel-1 acquisition over this AOI between 12 and 26 August; nearest is
    3 September" can act. A user who is told "error" cannot.
    """

    outcome: Literal["abstained"] = "abstained"
    reason: AbstentionReason
    #: Human-readable explanation. Rendered from a template over the execution
    #: trace, never generated by a language model -- see the P3 audit, issue I-3.
    explanation: str = Field(min_length=1)
    #: Nearest date for which an answer would be possible, when one exists.
    nearest_usable: datetime | None
    #: Scenes that were examined before declining. May be empty when nothing was
    #: found at all, which is itself informative.
    scenes_seen: list[SceneRef]
    trace_id: str = Field(min_length=1)


class Analysis(Strict):
    """A completed analysis.

    ``measurements`` and ``scenes`` both have ``min_length=1``: an analysis that
    measured nothing, or that cannot say which observations it used, is not an
    analysis. Those two constraints are what make this type unable to represent a
    fabricated result.

    ``confidence`` may be ``None`` -- see :mod:`ml.contracts.confidence`.
    A missing confidence is honest; an invented one is not.

    ``degraded_from`` records when this result came from a fallback path (for
    example, the learned model timed out and the deterministic baseline produced
    this instead). It is surfaced to the user rather than hidden, because a result
    produced by a simpler method is still a real result but the reader should know.
    """

    outcome: Literal["analysed"] = "analysed"
    measurements: list[Measurement] = Field(min_length=1)
    #: Object-storage key for the vectorised extent (GeoJSON).
    geometry_ref: str | None
    #: Object-storage keys for produced rasters (masks, composites).
    raster_refs: list[str]
    confidence: Confidence | None
    scenes: list[SceneRef] = Field(min_length=1)
    #: Name of the method that actually produced this, when a fallback was used.
    #: ``None`` means the primary path ran.
    degraded_from: str | None
    #: Plausibility flags carried up from postprocessing.
    caveats: list[str]
    trace_id: str = Field(min_length=1)


#: Every analysis entry point returns this union and nothing else.
#:
#: The discriminator lets pydantic pick the right member from the ``outcome``
#: field when deserialising, and -- more importantly -- makes it impossible for a
#: caller to forget that abstention is a possibility. Static analysis will flag an
#: unhandled branch.
MissionOutcome = Annotated[Analysis | Abstention, Field(discriminator="outcome")]
