"use client";

/**
 * Four numbers, each copied from a table in reports/evaluation.md.
 *
 * The fourth is deliberately a number we refuse to use. Water is ~11% of the pixels,
 * so a model that predicts no water anywhere is 89.2% "accurate" and useless. Putting
 * that figure on the page, struck through, is the fastest way to show a judge that
 * the other three were chosen to be hard to game.
 */

import { ACCURACY_TRAP, HEADLINE, f3 } from "../facts";
import { CountUp, Reveal, useSpotlight } from "../ui";

function Card({ children, delay }: { children: React.ReactNode; delay: number }) {
  const ref = useSpotlight<HTMLDivElement>();
  return (
    <Reveal delay={delay}>
      <div ref={ref} className="sq-card sq-proof-card">
        {children}
      </div>
    </Reveal>
  );
}

export function Proof() {
  const x = HEADLINE.pooledIoU / HEADLINE.baselinePooledIoU;
  return (
    <section id="proof" className="sq-section">
      <div className="sq-wrap">
        <Reveal className="sq-section-head">
          <span className="sq-eyebrow">Measured, not claimed</span>
          <h2 className="sq-h2">
            Numbers you can trace <span className="sq-grad-text">to a report.</span>
          </h2>
          <p className="sq-sub">
            Every figure on this page is generated by the evaluation pipeline, and CI fails
            the build if the report no longer matches the code that produced it.
          </p>
        </Reveal>

        <div className="sq-proof">
          <Card delay={0}>
            <div className="sq-proof-num sq-grad-text">
              <CountUp to={HEADLINE.pooledIoU} decimals={3} />
            </div>
            <div className="sq-proof-label">IoU on regions it never trained on</div>
            <div className="sq-proof-note">
              Pooled over India and Somalia. The classical baseline scores{" "}
              {f3(HEADLINE.baselinePooledIoU)}.
            </div>
          </Card>

          <Card delay={0.08}>
            <div className="sq-proof-num">
              <CountUp to={x} decimals={1} suffix="×" />
            </div>
            <div className="sq-proof-label">the classical baseline, on the same unseen chips</div>
            <div className="sq-proof-note">
              Otsu log-ratio thresholding, run on exactly the same chips.
            </div>
          </Card>

          <Card delay={0.16}>
            <div className="sq-proof-num">
              <CountUp to={HEADLINE.heldOutChips} />
            </div>
            <div className="sq-proof-label">held-out chips, split by region, not by chip</div>
            <div className="sq-proof-note">
              A chip-level split lets a model score well by recognising terrain it has
              already seen. {HEADLINE.chipsScored} of {HEADLINE.chipsFetched} chips scored.
            </div>
          </Card>

          <Card delay={0.24}>
            <div className="sq-proof-num is-struck">{ACCURACY_TRAP.predictNothingAccuracyPct}%</div>
            <div className="sq-proof-label">
              &ldquo;accuracy&rdquo; of a model that predicts no water at all
            </div>
            <div className="sq-proof-note">
              Accuracy is not quoted: water is {ACCURACY_TRAP.waterFractionPct}% of the pixels,
              so doing nothing scores {ACCURACY_TRAP.predictNothingAccuracyPct}% and an IoU of{" "}
              {ACCURACY_TRAP.predictNothingIoU.toFixed(3)}.
            </div>
          </Card>
        </div>
      </div>
    </section>
  );
}
